#!/usr/bin/env python3
"""
Build EXE + Inno Setup Installer for Archiver
Usage:
    python build_exe.py              # build EXE only
    python build_exe.py --iss        # generate .iss only
    python build_exe.py --setup      # build EXE + compile .iss
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
DIST = ROOT / "dist"
BUILD = ROOT / "build_temp"
ARCH_PKG = ROOT / "arch"
APP_NAME = "Archiver"
APP_VERSION = "0.2.0"
PUBLISHER = "Archiver Team"


def clean_build():
    for d in [BUILD]:
        if d.exists():
            shutil.rmtree(d)
    for p in DIST.glob("*.spec"):
        p.unlink()


def create_runtime_hook() -> Path:
    hook = BUILD / "_arch_hook.py"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(r'''"""PyInstaller runtime hook — redirects data paths to install dir."""
import sys
from pathlib import Path

if getattr(sys, "frozen", False):
    app_dir = Path(sys.executable).parent.resolve()
    import arch.config as _cfg
    _cfg.BASE_DIR = app_dir
    _cfg.DATA_DIR = app_dir / "data"
    _cfg.DB_PATH = _cfg.DATA_DIR / "arch.db"
    _cfg.LOG_PATH = _cfg.DATA_DIR / "arch.log"
    _cfg.KEY_PATH = _cfg.DATA_DIR / ".arch_key"
    _cfg.ARCHIVES_DIR = _cfg.DATA_DIR / "archives"
    _cfg.BACKUP_DIR = _cfg.DATA_DIR / "backups"
''', encoding="utf-8")
    return hook


def build_exe():
    print("=" * 60)
    print(f"  Building {APP_NAME} v{APP_VERSION} EXE")
    print("=" * 60)

    clean_build()
    DIST.mkdir(parents=True, exist_ok=True)
    hook = create_runtime_hook()

    entry = BUILD / "_arch_entry.py"
    entry.write_text('''"""Entry point for PyInstaller bundle."""
import sys
from pathlib import Path

if getattr(sys, "frozen", False):
    sys.path.insert(0, str(Path(sys.executable).parent))

import threading
import webbrowser

def _start_web(host="127.0.0.1", port=8080):
    threading.Timer(1.5, lambda: webbrowser.open(f"http://{host}:{port}")).start()
    from arch.web import serve
    serve(host=host, port=port)

if len(sys.argv) <= 1:
    _start_web()
elif sys.argv[1] == "web":
    host = "127.0.0.1"
    port = 8080
    for i, arg in enumerate(sys.argv[2:], 2):
        if arg == "--host" and i + 1 < len(sys.argv):
            host = sys.argv[i + 1]
        elif arg == "--port" and i + 1 < len(sys.argv):
            try:
                port = int(sys.argv[i + 1])
            except ValueError:
                pass
    _start_web(host, port)
else:
    from arch.__main__ import main
    main()
''', encoding="utf-8")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onedir",
        "--name", f"{APP_NAME.lower()}",
        "--distpath", str(DIST),
        "--workpath", str(BUILD / "pyi_work"),
        "--specpath", str(BUILD),
        "--add-data", f"{ARCH_PKG}{os.pathsep}arch",
        "--add-data", f"{ROOT / 'arch.ico'}{os.pathsep}.",
        "--add-data", f"{ROOT / 'readme.txt'}{os.pathsep}.",
        "--icon", str(ROOT / "arch.ico"),
        "--runtime-hook", str(hook),
        "--noconfirm",
        "--clean",
        str(entry),
    ]

    subprocess.check_call(cmd, cwd=ROOT)

    exe_dir = DIST / f"{APP_NAME.lower()}"
    if not (exe_dir / f"{APP_NAME.lower()}.exe").exists():
        print("ERROR: EXE not found after build!")
        sys.exit(1)

    print(f"\nEXE built: {exe_dir / f'{APP_NAME.lower()}.exe'}")
    return exe_dir


def generate_iss(exe_dir: Path) -> Path:
    print("\n" + "=" * 60)
    print("  Generating Inno Setup script (.iss)")
    print("=" * 60)

    exe_path = exe_dir / f"{APP_NAME.lower()}.exe"
    app_dir = f"{APP_NAME}"
    data_dir = "{app}\\data"
    setup_iss = ROOT / "setupInno.iss"

    iss_content = f"""; Archiver Inno Setup Installer Script
; Generated by build_exe.py — professional silent installer

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "{PUBLISHER}"
#define MyAppURL "https://github.com/example/archiver"
#define MyAppExe "{APP_NAME.lower()}.exe"
#define MyAppIcon "arch.ico"

[Setup]
AppId={{{{8B6E2F4A-1D3C-4E5F-9A7B-2C8D6E0F1A3B}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppVerName={{#MyAppName}} {{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
AppCopyright=Copyright (C) 2026 {{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
DisableProgramGroupPage=yes
AllowNoIcons=yes
SetupIconFile={ROOT / 'arch.ico'}
UninstallDisplayIcon={{app}}\\arch.ico
UninstallDisplaySize=20480
Compression=lzma
SolidCompression=yes
OutputDir={DIST}
OutputBaseFilename={APP_NAME}-Setup-v{APP_VERSION}
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x86compatible x64compatible arm64
ArchitecturesInstallIn64BitMode=x64compatible arm64
MinVersion=10.0
AppMutex=ArchiverAppMutex
VersionInfoVersion={APP_VERSION}.0
VersionInfoCompany={{#MyAppPublisher}}
VersionInfoDescription=Professional Archiving System (Secure Edition)
VersionInfoProductName={{#MyAppName}}
VersionInfoProductVersion={APP_VERSION}.0
VersionInfoCopyright=Copyright (C) 2026 {{#MyAppPublisher}}
InfoAfterFile=readme.txt
; Always create data directory
DirExistsWarning=no

[Languages]
Name: "arabic"; MessagesFile: "compiler:Languages\\Arabic.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{{cm:CreateQuickLaunchIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked
Name: "autostart"; Description: "تشغيل الخادم تلقائياً بعد التثبيت"; GroupDescription: "خيارات التشغيل:"

[Files]
; PyInstaller output directory — all EXE + DLLs + Python libs
Source: "{exe_dir}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pyc,__pycache__"

; Root files
Source: "{ROOT / 'arch.ico'}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{ROOT / 'readme.txt'}"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\{{#MyAppName}} CLI"; Filename: "{{app}}\\{{#MyAppExe}}"; WorkingDir: "{{app}}"; IconFilename: "{{app}}\\arch.ico"; Comment: "Archiver — سطر الأوامر"
Name: "{{group}}\\{{#MyAppName}} Web UI"; Filename: "{{app}}\\{{#MyAppExe}}"; Parameters: "web"; WorkingDir: "{{app}}"; IconFilename: "{{app}}\\arch.ico"; Comment: "Archiver — واجهة الويب"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"; IconFilename: "{{app}}\\arch.ico"
Name: "{{autodesktop}}\\{{#MyAppName}} CLI"; Filename: "{{app}}\\{{#MyAppExe}}"; WorkingDir: "{{app}}"; IconFilename: "{{app}}\\arch.ico"; Tasks: desktopicon
Name: "{{autodesktop}}\\{{#MyAppName}} Web UI"; Filename: "{{app}}\\{{#MyAppExe}}"; Parameters: "web"; WorkingDir: "{{app}}"; IconFilename: "{{app}}\\arch.ico"; Tasks: desktopicon

[Dirs]
Name: "{{app}}\\data"
Name: "{{app}}\\data\\archives"
Name: "{{app}}\\data\\backups"

[Run]
; Start web server silently in background (hidden window)
Filename: "{{app}}\\{{#MyAppExe}}"; Parameters: "web"; WorkingDir: "{{app}}"; Description: "بدء خادم الويب"; Flags: nowait skipifsilent hidewizard; Tasks: autostart
; Open browser to the web UI automatically
Filename: "http://127.0.0.1:8080"; Description: "فتح واجهة الويب"; Flags: nowait skipifsilent shellexec; Tasks: autostart

[UninstallDelete]
Type: filesandordirs; Name: "{{app}}\\data"
Type: filesandordirs; Name: "{{app}}\\__pycache__"
Type: filesandordirs; Name: "{{app}}\\arch\\__pycache__"
Type: filesandordirs; Name: "{{app}}"
"""

    setup_iss.write_text(iss_content, encoding="utf-8")
    print(f".iss generated: {setup_iss}")
    return setup_iss


def compile_iss(iss_path: Path):
    iscc = r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
    if not Path(iscc).exists():
        print("Inno Setup Compiler (ISCC.exe) not found. Skipping compilation.")
        print(f"  Expected at: {iscc}")
        print("  You can manually compile: ISCC.exe setupInno.iss")
        return False
    print("\n" + "=" * 60)
    print("  Compiling Inno Setup installer...")
    print("=" * 60)
    subprocess.check_call([iscc, str(iss_path)], cwd=ROOT)

    exe_name = f"{APP_NAME}-Setup-v{APP_VERSION}.exe"
    installer = DIST / exe_name
    if installer.exists():
        print(f"\nInstaller created: {installer}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Build Archiver EXE + Installer")
    parser.add_argument("--setup", action="store_true", help="Build EXE + compile .iss installer")
    parser.add_argument("--iss", action="store_true", help="Generate .iss only (requires existing EXE in dist/)")
    parser.add_argument("--exe-only", action="store_true", help="Build EXE only (default)")
    args = parser.parse_args()

    if args.iss:
        exe_dir = DIST / f"{APP_NAME.lower()}"
        generate_iss(exe_dir)
        return

    if args.setup:
        exe_dir = build_exe()
        iss_path = generate_iss(exe_dir)
        compile_iss(iss_path)
        print(f"\n{'=' * 60}")
        print(f"  Done! Installer: {DIST / f'{APP_NAME}-Setup-v{APP_VERSION}.exe'}")
        print(f"  EXE: {exe_dir / f'{APP_NAME.lower()}.exe'}")
        print(f"{'=' * 60}")
        return

    # Default: build EXE only
    exe_dir = build_exe()
    generate_iss(exe_dir)
    print(f"\n{'=' * 60}")
    print(f"  Done! EXE: {exe_dir / f'{APP_NAME.lower()}.exe'}")
    print(f"  .iss: {ROOT / 'setupInno.iss'}")
    print(f"  Run 'python build_exe.py --setup' to compile the installer.")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
